-- MySQL Script generated by MySQL Workbench
-- Do 28 Apr 2016 22:31:08 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema myUPMsocial
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema myUPMsocial
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `myUPMsocial` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `myUPMsocial` ;

-- -----------------------------------------------------
-- Table `myUPMsocial`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `myUPMsocial`.`usuario` ;

CREATE TABLE IF NOT EXISTS `myUPMsocial`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myUPMsocial`.`post`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `myUPMsocial`.`post` ;

CREATE TABLE IF NOT EXISTS `myUPMsocial`.`post` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `date` CHAR(10) NULL COMMENT '',
  `content` VARCHAR(45) NULL COMMENT '',
  `usuario_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_post_usuario_idx` (`usuario_id` ASC)  COMMENT '',
  CONSTRAINT `fk_post_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `myUPMsocial`.`usuario` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myUPMsocial`.`amigos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `myUPMsocial`.`amigos` ;

CREATE TABLE IF NOT EXISTS `myUPMsocial`.`amigos` (
  `usuario1_id` INT NOT NULL COMMENT '',
  `usuario2_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`usuario1_id`, `usuario2_id`)  COMMENT '',
  INDEX `fk_usuario_has_usuario_usuario2_idx` (`usuario2_id` ASC)  COMMENT '',
  INDEX `fk_usuario_has_usuario_usuario1_idx` (`usuario1_id` ASC)  COMMENT '',
  CONSTRAINT `fk_usuario_has_usuario_usuario1`
    FOREIGN KEY (`usuario1_id`)
    REFERENCES `myUPMsocial`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_has_usuario_usuario2`
    FOREIGN KEY (`usuario2_id`)
    REFERENCES `myUPMsocial`.`usuario` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
